"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Events = {
    join: "join",
    leave: "leave",
    newTx: "NEW_TX",
    newPendingTx: "NEW_PENDING_TX",
    newBlock: "NEW_BLOCK",
    pastTxs: "get-past-txs",
    pastTxsR: "PAST_TXS_RECEIVED",
    pastBlocks: "get-past-blocks",
    getBalance: "get-balance",
    getTokenBalance: "get-tokens-balance",
    getTotalTxs: "get-total-txs",
    getTicker: "getTicker",
    getTxs: "get-txs",
    getTx: "get-tx",
    getBlock: "get-block",
    getBlockTransactions: "get-block-txs",
    getAccount: "get-account",
    pendingTxs: "get-pending-txs",
    pendingTxsAddress: "getPendingTxs",
    getUncle: "get-uncle",
    getUncles: "get-uncles",
    newUncle: "NEW_UNCLE",
    ethCall: "eth-call",
    pastBlocksR: "PAST_BLOCKS_RECEIVED",
    getBlocksMined: "get-blocks-mined",
    getAddressTxs: "get-address-txs",
    getAddressPendingTxs: "get-address-pending-txs",
    getCurrentStateRoot: "get-current-state-root",
    getExchangeRates: "get-exchange-rates",
    search: "search"
};
