---
molecule:
  # directory in CWD to place all temp files, etc.
  molecule_dir: .molecule

  # where temporary state will be stored (lives under molecule_dir)
  state_file: state

  # name of temporary vagrantfile created during runs (lives under molecule_dir)
  vagrantfile_file: vagrantfile

  # directories to ignore when doing trailing whitespace checks on files during verify command
  ignore_paths:
    - .git
    - .vagrant
    - .molecule

  # directory containing group_vars to use with ansible
  group_vars: ../tests/group_vars

  test:
    sequence:
      - destroy
      - syntax
      - create
      - converge
      - idempotence
      - verify
      - destroy

  # directory to look for goss tests
  goss_dir: tests/goss
  goss_playbook: verifier.yml

dependency:
  name: galaxy
  requirements_file: tests/requirements.yml

# ansible related configuration
ansible:
  playbook: tests/playbook.yml

verifier:
  name: goss

# configuration options for the internal call to vagrant
vagrant:
  raw_config_args:
    - "hostmanager.enabled = true"
    # Enable for debug purpose
    #- "hostmanager.manage_host = true"
    - "hostmanager.manage_guest = true"
    - "hostmanager.ignore_private_ip = false"
    - "hostmanager.include_offline = true"
  # molecule's --platform option will look for these names
  platforms:
    - name: Debian
      box: debian/jessie64
    - name: Debian
      box: debian/stretch64

  providers:
    - name: virtualbox
      type: virtualbox
      options:
        memory: 1024
        cpus: 1

  instances:
    - name: zookeeper1
      ansible_groups:
        - zookeeper
      interfaces:
        - network_name: private_network
          type: static
          ip: 172.28.128.61
          auto_config: true
    - name: zookeeper2
      ansible_groups:
        - zookeeper
      interfaces:
        - network_name: private_network
          type: static
          ip: 172.28.128.62
          auto_config: true
    - name: zookeeper3
      ansible_groups:
        - zookeeper
      interfaces:
        - network_name: private_network
          type: static
          ip: 172.28.128.63
          auto_config: true

docker:
  network:
    - name: docker-cluster-network
      driver: bridge
  containers:
    - name: zookeeper1
      hostname: zookeeper1
      ansible_groups:
        - zookeeper
      image: idealista/java-debian-ansible
      image_version: latest
      network_mode: docker-cluster-network
      # All these parameters are needed for Docker testing with systemd
      privileged: True
      cap_add:
        - SYS_ADMIN
      volume_mounts:
        - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
      command: '/lib/systemd/systemd'

    - name: zookeeper2
      hostname: zookeeper2
      ansible_groups:
        - zookeeper
      image: idealista/java-debian-ansible
      image_version: latest
      network_mode: docker-cluster-network
      # All these parameters are needed for Docker testing with systemd
      privileged: True
      cap_add:
        - SYS_ADMIN
      volume_mounts:
        - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
      command: '/lib/systemd/systemd'

    - name: zookeeper3
      hostname: zookeeper3
      ansible_groups:
        - zookeeper
      image: idealista/java-debian-ansible
      image_version: latest
      network_mode: docker-cluster-network
      # All these parameters are needed for Docker testing with systemd
      privileged: True
      cap_add:
        - SYS_ADMIN
      volume_mounts:
        - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
      command: '/lib/systemd/systemd'
