version: '3.6'

volumes:
  ethereumj-volume:

services:

  mongodb:
    volumes:
      - ./datasets:/datasets

  ethereumj:
    build:
      context: ./apps/ethereumj
    restart: on-failure:3
    volumes:
      - ethereumj-volume:/ethj
      - ./provisioners/docker/config/ethereumj/kafka-ropsten.conf:/ethereumj/ethereumj-core/src/main/resources/kafka-ethereumj.conf
      - ./provisioners/docker/config/ethereumj/kafka-ropsten.conf:/ethereumj/ethereumj-core/src/main/resources/kafka-private-net.conf
      - ./provisioners/docker/config/ethereumj/kafka-ropsten.conf:/ethereumj/ethereumj-core/src/main/resources/kafka-ropsten.conf
    networks:
      back:
        ipv4_address: 172.25.0.102
    # -- Select one of these options to connect to different networks: MainNet or Ropsten
    command: ./gradlew --no-daemon run -PmainClass=io.enkrypt.kafka.EthereumKafkaStarter
    #command: ./gradlew --no-daemon run -PmainClass=io.enkrypt.kafka.EthereumRopstenKafkaStarter

  bolt:
    build:
      context: ./apps/bolt
    restart: on-failure:3
    networks:
      - back
    environment:
      KAFKA_BOOTSTRAP_SERVERS: 'kafka:9092'
      MONGO_URI: 'mongodb://mongodb:27017/ethvm_local'
