---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ssd
parameters:
  type: pd-ssd
provisioner: kubernetes.io/gce-pd
reclaimPolicy: Retain

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: ethvm
  name: geth-mainnet-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  # storageClassName: ssd
  storageClassName: standard # minikube

---

apiVersion: v1
kind: Service
metadata:
  namespace: ethvm
  name: geth-rpc
  labels:
    name: geth-rpc
spec:
  ports:
    - name: geth-rpc
      protocol: TCP
      port: 9545
      targetPort: 9545
  selector:
    app: geth

---

apiVersion: v1
kind: Service
metadata:
  namespace: ethvm
  name: geth-mainnet-p2p
  labels:
    name: geth-mainnet-p2p
spec:
  ports:
    - name: geth-mainnet-p2p
      protocol: TCP
      port: 30303
      targetPort: 30303
  # type: LoadBalancer
  type: NodePort # minikube
  selector:
    geth: mainnet

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ethvm
  name: geth-mainnet
  labels:
    app: geth
    geth: mainnet
spec:
  selector:
    matchLabels:
      app: geth
  replicas: 1
  template:
    metadata:
      labels:
        app: geth
        geth: mainnet
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: geth
                operator: In
                values:
                - backup
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: geth
        image: enkryptio/go-ethereum
        ports:
        - containerPort: 8545
        - containerPort: 30303
        volumeMounts:
        - mountPath: /usr/share/geth
          name: geth-pd
        command:
        - geth
        args:
        - --datadir="/usr/share/geth"
        - --rpc
        - --rpcaddr=0.0.0.0
        - --rpcport=8545
        - --rpcapi=eth,web3,net
        - --maxpeers=25
        - --gcmode=archive
        - --syncmode=full
        - --nousb
        - --rinkeby # minikube
      volumes:
      - name: geth-pd
        persistentVolumeClaim:
          claimName: geth-mainnet-data
