// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCES:
 *     block.schema.v1.asvc
 *     pendingtx.schema.v1.asvc
 */

package ethvm

type UnionAction struct {
	Action    Action
	UnionType UnionActionTypeEnum
}

type UnionActionTypeEnum int

const (
	UnionActionTypeEnumAction UnionActionTypeEnum = 0
)
