{
 "title": "Kafka Connect Sink Lag",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Block Header & Uncle",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  topic AS metric,\n  lag\nFROM kafka_offset_info_log_grafana\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  consumer_group_id = 'connect-postgres-block-header-and-uncle-sink'\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Tx & Receipt",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  topic AS metric,\n  lag\nFROM kafka_offset_info_log_grafana\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  consumer_group_id = 'connect-postgres-tx-and-receipt-sink'\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Traces",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  topic AS metric,\n  lag\nFROM kafka_offset_info_log_grafana\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  consumer_group_id = 'connect-postgres-trace-sink'\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Contract",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  topic AS metric,\n  lag\nFROM kafka_offset_info_log_grafana\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  consumer_group_id = 'connect-postgres-contract-sink'\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Balance",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  topic AS metric,\n  lag\nFROM kafka_offset_info_log_grafana\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  consumer_group_id = 'connect-postgres-balance-delta-sink'\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Block Metrics",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  topic AS metric,\n  lag\nFROM kafka_offset_info_log_grafana\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  consumer_group_id = 'connect-block-metrics-sink'\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Parity Sync State",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  topic AS metric,\n  lag\nFROM kafka_offset_info_log_grafana\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  consumer_group_id = 'connect-postgres-parity-sync-state-log'\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Kafka Offset Info",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  topic AS metric,\n  lag\nFROM kafka_offset_info_log_grafana\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  consumer_group_id = 'connect-postgres-kafka-offset-info-log'\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Exchange Rates",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  topic AS metric,\n  lag\nFROM kafka_offset_info_log_grafana\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  consumer_group_id = 'connect-postgres-exchange-rates-sink'\nORDER BY 1,2"
    }
   ]
  }
 ]
}