{
 "title": "Kafka Connect Parity Lag",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Blocks, Txs & Uncles ",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  lag\nFROM parity_sync_state_log_grafana\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  source = 'block'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Receipts",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  lag\nFROM parity_sync_state_log_grafana\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  source = 'receipt'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Traces",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  lag\nFROM parity_sync_state_log_grafana\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  source = 'trace'\nORDER BY 1"
    }
   ]
  }
 ]
}