{
 "title": "Kafka Streams Processing Lag",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Flat Map",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  topic AS metric,\n  lag\nFROM kafka_offset_info_log_grafana\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  consumer_group_id = 'flat-map-processor'\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Fungible Balance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  topic AS metric,\n  lag\nFROM kafka_offset_info_log_grafana\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  consumer_group_id = 'fungible-balance-processor'\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Transaction Fees",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  topic AS metric,\n  lag\nFROM kafka_offset_info_log_grafana\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  consumer_group_id = 'transaction-fees-processor'\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Non Fungible Balance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  topic AS metric,\n  lag\nFROM kafka_offset_info_log_grafana\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  consumer_group_id = 'non-fungible-balance-processor'\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Contract Lifecycle",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  topic AS metric,\n  lag\nFROM kafka_offset_info_log_grafana\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  consumer_group_id = 'contract-lifecycle-processor'\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Contract Metadata",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  topic AS metric,\n  lag\nFROM kafka_offset_info_log_grafana\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  consumer_group_id = 'contract-metadata-processor'\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Block Metrics",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  topic AS metric,\n  lag\nFROM kafka_offset_info_log_grafana\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  consumer_group_id = 'block-metrics-processor'\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Block Author",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  topic AS metric,\n  lag\nFROM kafka_offset_info_log_grafana\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  consumer_group_id = 'block-author-processor'\nORDER BY 1,2"
    }
   ]
  }
 ]
}