{
 "title": "Kafka Overview",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Block Headers Offset",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_topic_partition_current_offset{partition=\"0\",topic=\"canonical_block_header\"}"
    }
   ]
  },
  {
   "title": "Processor Lag",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{consumergroup=~\".*-processor\"}) by (consumergroup)   "
    }
   ]
  },
  {
   "title": "Connector Lag",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{consumergroup=~\"connect-.*\"}) by (consumergroup)   "
    }
   ]
  }
 ]
}