/*
 * This file is generated by jOOQ.
 */
package com.ethvm.db.tables;


import com.ethvm.db.Indexes;
import com.ethvm.db.Keys;
import com.ethvm.db.Public;
import com.ethvm.db.tables.records.AddressContractsCreatedCountDeltaRecord;

import java.math.BigDecimal;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AddressContractsCreatedCountDelta extends TableImpl<AddressContractsCreatedCountDeltaRecord> {

    private static final long serialVersionUID = 1544767296;

    /**
     * The reference instance of <code>public.address_contracts_created_count_delta</code>
     */
    public static final AddressContractsCreatedCountDelta ADDRESS_CONTRACTS_CREATED_COUNT_DELTA = new AddressContractsCreatedCountDelta();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AddressContractsCreatedCountDeltaRecord> getRecordType() {
        return AddressContractsCreatedCountDeltaRecord.class;
    }

    /**
     * The column <code>public.address_contracts_created_count_delta.id</code>.
     */
    public final TableField<AddressContractsCreatedCountDeltaRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('address_contracts_created_count_delta_id_seq'::regclass)", org.jooq.impl.SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.address_contracts_created_count_delta.address</code>.
     */
    public final TableField<AddressContractsCreatedCountDeltaRecord, String> ADDRESS = createField("address", org.jooq.impl.SQLDataType.CHAR(42), this, "");

    /**
     * The column <code>public.address_contracts_created_count_delta.block_number</code>.
     */
    public final TableField<AddressContractsCreatedCountDeltaRecord, BigDecimal> BLOCK_NUMBER = createField("block_number", org.jooq.impl.SQLDataType.NUMERIC.nullable(false), this, "");

    /**
     * The column <code>public.address_contracts_created_count_delta.delta</code>.
     */
    public final TableField<AddressContractsCreatedCountDeltaRecord, Integer> DELTA = createField("delta", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>public.address_contracts_created_count_delta</code> table reference
     */
    public AddressContractsCreatedCountDelta() {
        this(DSL.name("address_contracts_created_count_delta"), null);
    }

    /**
     * Create an aliased <code>public.address_contracts_created_count_delta</code> table reference
     */
    public AddressContractsCreatedCountDelta(String alias) {
        this(DSL.name(alias), ADDRESS_CONTRACTS_CREATED_COUNT_DELTA);
    }

    /**
     * Create an aliased <code>public.address_contracts_created_count_delta</code> table reference
     */
    public AddressContractsCreatedCountDelta(Name alias) {
        this(alias, ADDRESS_CONTRACTS_CREATED_COUNT_DELTA);
    }

    private AddressContractsCreatedCountDelta(Name alias, Table<AddressContractsCreatedCountDeltaRecord> aliased) {
        this(alias, aliased, null);
    }

    private AddressContractsCreatedCountDelta(Name alias, Table<AddressContractsCreatedCountDeltaRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> AddressContractsCreatedCountDelta(Table<O> child, ForeignKey<O, AddressContractsCreatedCountDeltaRecord> key) {
        super(child, key, ADDRESS_CONTRACTS_CREATED_COUNT_DELTA);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.ADDRESS_CONTRACTS_CREATED_COUNT_DELTA_ADDRESS_BLOCK_NUMBER_KEY, Indexes.ADDRESS_CONTRACTS_CREATED_COUNT_DELTA_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<AddressContractsCreatedCountDeltaRecord, Long> getIdentity() {
        return Keys.IDENTITY_ADDRESS_CONTRACTS_CREATED_COUNT_DELTA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<AddressContractsCreatedCountDeltaRecord> getPrimaryKey() {
        return Keys.ADDRESS_CONTRACTS_CREATED_COUNT_DELTA_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<AddressContractsCreatedCountDeltaRecord>> getKeys() {
        return Arrays.<UniqueKey<AddressContractsCreatedCountDeltaRecord>>asList(Keys.ADDRESS_CONTRACTS_CREATED_COUNT_DELTA_PKEY, Keys.ADDRESS_CONTRACTS_CREATED_COUNT_DELTA_ADDRESS_BLOCK_NUMBER_KEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AddressContractsCreatedCountDelta as(String alias) {
        return new AddressContractsCreatedCountDelta(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AddressContractsCreatedCountDelta as(Name alias) {
        return new AddressContractsCreatedCountDelta(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public AddressContractsCreatedCountDelta rename(String name) {
        return new AddressContractsCreatedCountDelta(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AddressContractsCreatedCountDelta rename(Name name) {
        return new AddressContractsCreatedCountDelta(name, null);
    }
}
