/*
 * This file is generated by jOOQ.
 */
package com.ethvm.db.tables;


import com.ethvm.db.Public;
import com.ethvm.db.tables.records.CanonicalTokenExchangeRateRecord;

import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CanonicalTokenExchangeRate extends TableImpl<CanonicalTokenExchangeRateRecord> {

    private static final long serialVersionUID = 1500743864;

    /**
     * The reference instance of <code>public.canonical_token_exchange_rate</code>
     */
    public static final CanonicalTokenExchangeRate CANONICAL_TOKEN_EXCHANGE_RATE = new CanonicalTokenExchangeRate();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CanonicalTokenExchangeRateRecord> getRecordType() {
        return CanonicalTokenExchangeRateRecord.class;
    }

    /**
     * The column <code>public.canonical_token_exchange_rate.address</code>.
     */
    public final TableField<CanonicalTokenExchangeRateRecord, String> ADDRESS = createField("address", org.jooq.impl.SQLDataType.CHAR(42), this, "");

    /**
     * The column <code>public.canonical_token_exchange_rate.symbol</code>.
     */
    public final TableField<CanonicalTokenExchangeRateRecord, String> SYMBOL = createField("symbol", org.jooq.impl.SQLDataType.VARCHAR(128), this, "");

    /**
     * The column <code>public.canonical_token_exchange_rate.name</code>.
     */
    public final TableField<CanonicalTokenExchangeRateRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(128), this, "");

    /**
     * The column <code>public.canonical_token_exchange_rate.image</code>.
     */
    public final TableField<CanonicalTokenExchangeRateRecord, String> IMAGE = createField("image", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.canonical_token_exchange_rate.current_price</code>.
     */
    public final TableField<CanonicalTokenExchangeRateRecord, BigDecimal> CURRENT_PRICE = createField("current_price", org.jooq.impl.SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>public.canonical_token_exchange_rate.market_cap</code>.
     */
    public final TableField<CanonicalTokenExchangeRateRecord, BigDecimal> MARKET_CAP = createField("market_cap", org.jooq.impl.SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>public.canonical_token_exchange_rate.market_cap_rank</code>.
     */
    public final TableField<CanonicalTokenExchangeRateRecord, Integer> MARKET_CAP_RANK = createField("market_cap_rank", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.canonical_token_exchange_rate.total_volume</code>.
     */
    public final TableField<CanonicalTokenExchangeRateRecord, BigDecimal> TOTAL_VOLUME = createField("total_volume", org.jooq.impl.SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>public.canonical_token_exchange_rate.high24h</code>.
     */
    public final TableField<CanonicalTokenExchangeRateRecord, BigDecimal> HIGH24H = createField("high24h", org.jooq.impl.SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>public.canonical_token_exchange_rate.low24h</code>.
     */
    public final TableField<CanonicalTokenExchangeRateRecord, BigDecimal> LOW24H = createField("low24h", org.jooq.impl.SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>public.canonical_token_exchange_rate.price_change24h</code>.
     */
    public final TableField<CanonicalTokenExchangeRateRecord, BigDecimal> PRICE_CHANGE24H = createField("price_change24h", org.jooq.impl.SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>public.canonical_token_exchange_rate.price_change_percentage24h</code>.
     */
    public final TableField<CanonicalTokenExchangeRateRecord, BigDecimal> PRICE_CHANGE_PERCENTAGE24H = createField("price_change_percentage24h", org.jooq.impl.SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>public.canonical_token_exchange_rate.market_cap_change24h</code>.
     */
    public final TableField<CanonicalTokenExchangeRateRecord, BigDecimal> MARKET_CAP_CHANGE24H = createField("market_cap_change24h", org.jooq.impl.SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>public.canonical_token_exchange_rate.market_cap_change_percentage24h</code>.
     */
    public final TableField<CanonicalTokenExchangeRateRecord, BigDecimal> MARKET_CAP_CHANGE_PERCENTAGE24H = createField("market_cap_change_percentage24h", org.jooq.impl.SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>public.canonical_token_exchange_rate.circulating_supply</code>.
     */
    public final TableField<CanonicalTokenExchangeRateRecord, BigDecimal> CIRCULATING_SUPPLY = createField("circulating_supply", org.jooq.impl.SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>public.canonical_token_exchange_rate.total_supply</code>.
     */
    public final TableField<CanonicalTokenExchangeRateRecord, BigDecimal> TOTAL_SUPPLY = createField("total_supply", org.jooq.impl.SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>public.canonical_token_exchange_rate.last_updated</code>.
     */
    public final TableField<CanonicalTokenExchangeRateRecord, Long> LAST_UPDATED = createField("last_updated", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * Create a <code>public.canonical_token_exchange_rate</code> table reference
     */
    public CanonicalTokenExchangeRate() {
        this(DSL.name("canonical_token_exchange_rate"), null);
    }

    /**
     * Create an aliased <code>public.canonical_token_exchange_rate</code> table reference
     */
    public CanonicalTokenExchangeRate(String alias) {
        this(DSL.name(alias), CANONICAL_TOKEN_EXCHANGE_RATE);
    }

    /**
     * Create an aliased <code>public.canonical_token_exchange_rate</code> table reference
     */
    public CanonicalTokenExchangeRate(Name alias) {
        this(alias, CANONICAL_TOKEN_EXCHANGE_RATE);
    }

    private CanonicalTokenExchangeRate(Name alias, Table<CanonicalTokenExchangeRateRecord> aliased) {
        this(alias, aliased, null);
    }

    private CanonicalTokenExchangeRate(Name alias, Table<CanonicalTokenExchangeRateRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> CanonicalTokenExchangeRate(Table<O> child, ForeignKey<O, CanonicalTokenExchangeRateRecord> key) {
        super(child, key, CANONICAL_TOKEN_EXCHANGE_RATE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CanonicalTokenExchangeRate as(String alias) {
        return new CanonicalTokenExchangeRate(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CanonicalTokenExchangeRate as(Name alias) {
        return new CanonicalTokenExchangeRate(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public CanonicalTokenExchangeRate rename(String name) {
        return new CanonicalTokenExchangeRate(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CanonicalTokenExchangeRate rename(Name name) {
        return new CanonicalTokenExchangeRate(name, null);
    }
}
