/*
 * This file is generated by jOOQ.
 */
package com.ethvm.db.tables;


import com.ethvm.db.Indexes;
import com.ethvm.db.Keys;
import com.ethvm.db.Public;
import com.ethvm.db.tables.records.TokenExchangeRateRecord;

import java.math.BigDecimal;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TokenExchangeRate extends TableImpl<TokenExchangeRateRecord> {

    private static final long serialVersionUID = 1210467730;

    /**
     * The reference instance of <code>public.token_exchange_rate</code>
     */
    public static final TokenExchangeRate TOKEN_EXCHANGE_RATE = new TokenExchangeRate();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TokenExchangeRateRecord> getRecordType() {
        return TokenExchangeRateRecord.class;
    }

    /**
     * The column <code>public.token_exchange_rate.address</code>.
     */
    public final TableField<TokenExchangeRateRecord, String> ADDRESS = createField("address", org.jooq.impl.SQLDataType.CHAR(42).nullable(false), this, "");

    /**
     * The column <code>public.token_exchange_rate.symbol</code>.
     */
    public final TableField<TokenExchangeRateRecord, String> SYMBOL = createField("symbol", org.jooq.impl.SQLDataType.VARCHAR(128), this, "");

    /**
     * The column <code>public.token_exchange_rate.name</code>.
     */
    public final TableField<TokenExchangeRateRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(128), this, "");

    /**
     * The column <code>public.token_exchange_rate.image</code>.
     */
    public final TableField<TokenExchangeRateRecord, String> IMAGE = createField("image", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.token_exchange_rate.current_price</code>.
     */
    public final TableField<TokenExchangeRateRecord, BigDecimal> CURRENT_PRICE = createField("current_price", org.jooq.impl.SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>public.token_exchange_rate.market_cap</code>.
     */
    public final TableField<TokenExchangeRateRecord, BigDecimal> MARKET_CAP = createField("market_cap", org.jooq.impl.SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>public.token_exchange_rate.market_cap_rank</code>.
     */
    public final TableField<TokenExchangeRateRecord, Integer> MARKET_CAP_RANK = createField("market_cap_rank", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.token_exchange_rate.total_volume</code>.
     */
    public final TableField<TokenExchangeRateRecord, BigDecimal> TOTAL_VOLUME = createField("total_volume", org.jooq.impl.SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>public.token_exchange_rate.high24h</code>.
     */
    public final TableField<TokenExchangeRateRecord, BigDecimal> HIGH24H = createField("high24h", org.jooq.impl.SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>public.token_exchange_rate.low24h</code>.
     */
    public final TableField<TokenExchangeRateRecord, BigDecimal> LOW24H = createField("low24h", org.jooq.impl.SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>public.token_exchange_rate.price_change24h</code>.
     */
    public final TableField<TokenExchangeRateRecord, BigDecimal> PRICE_CHANGE24H = createField("price_change24h", org.jooq.impl.SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>public.token_exchange_rate.price_change_percentage24h</code>.
     */
    public final TableField<TokenExchangeRateRecord, BigDecimal> PRICE_CHANGE_PERCENTAGE24H = createField("price_change_percentage24h", org.jooq.impl.SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>public.token_exchange_rate.market_cap_change24h</code>.
     */
    public final TableField<TokenExchangeRateRecord, BigDecimal> MARKET_CAP_CHANGE24H = createField("market_cap_change24h", org.jooq.impl.SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>public.token_exchange_rate.market_cap_change_percentage24h</code>.
     */
    public final TableField<TokenExchangeRateRecord, BigDecimal> MARKET_CAP_CHANGE_PERCENTAGE24H = createField("market_cap_change_percentage24h", org.jooq.impl.SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>public.token_exchange_rate.circulating_supply</code>.
     */
    public final TableField<TokenExchangeRateRecord, BigDecimal> CIRCULATING_SUPPLY = createField("circulating_supply", org.jooq.impl.SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>public.token_exchange_rate.total_supply</code>.
     */
    public final TableField<TokenExchangeRateRecord, BigDecimal> TOTAL_SUPPLY = createField("total_supply", org.jooq.impl.SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>public.token_exchange_rate.last_updated</code>.
     */
    public final TableField<TokenExchangeRateRecord, Long> LAST_UPDATED = createField("last_updated", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * Create a <code>public.token_exchange_rate</code> table reference
     */
    public TokenExchangeRate() {
        this(DSL.name("token_exchange_rate"), null);
    }

    /**
     * Create an aliased <code>public.token_exchange_rate</code> table reference
     */
    public TokenExchangeRate(String alias) {
        this(DSL.name(alias), TOKEN_EXCHANGE_RATE);
    }

    /**
     * Create an aliased <code>public.token_exchange_rate</code> table reference
     */
    public TokenExchangeRate(Name alias) {
        this(alias, TOKEN_EXCHANGE_RATE);
    }

    private TokenExchangeRate(Name alias, Table<TokenExchangeRateRecord> aliased) {
        this(alias, aliased, null);
    }

    private TokenExchangeRate(Name alias, Table<TokenExchangeRateRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> TokenExchangeRate(Table<O> child, ForeignKey<O, TokenExchangeRateRecord> key) {
        super(child, key, TOKEN_EXCHANGE_RATE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.IDX_TOKEN_EXCHANGE_RATES_ADDRESS, Indexes.IDX_TOKEN_EXCHANGE_RATES_CURRENT_PRICE, Indexes.IDX_TOKEN_EXCHANGE_RATES_CURRENT_PRICE_DESC, Indexes.IDX_TOKEN_EXCHANGE_RATES_MARKET_CAP, Indexes.IDX_TOKEN_EXCHANGE_RATES_MARKET_CAP_DESC, Indexes.IDX_TOKEN_EXCHANGE_RATES_MARKET_CAP_RANK, Indexes.IDX_TOKEN_EXCHANGE_RATES_SYMBOL, Indexes.IDX_TOKEN_EXCHANGE_RATES_TOTAL_VOLUME, Indexes.IDX_TOKEN_EXCHANGE_RATES_TOTAL_VOLUME_DESC, Indexes.TOKEN_EXCHANGE_RATE_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TokenExchangeRateRecord> getPrimaryKey() {
        return Keys.TOKEN_EXCHANGE_RATE_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TokenExchangeRateRecord>> getKeys() {
        return Arrays.<UniqueKey<TokenExchangeRateRecord>>asList(Keys.TOKEN_EXCHANGE_RATE_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TokenExchangeRate as(String alias) {
        return new TokenExchangeRate(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TokenExchangeRate as(Name alias) {
        return new TokenExchangeRate(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TokenExchangeRate rename(String name) {
        return new TokenExchangeRate(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TokenExchangeRate rename(Name name) {
        return new TokenExchangeRate(name, null);
    }
}
