/*
 * This file is generated by jOOQ.
 */
package com.ethvm.db.tables;


import com.ethvm.db.Indexes;
import com.ethvm.db.Keys;
import com.ethvm.db.Public;
import com.ethvm.db.tables.records.TransactionReceiptRecord;

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TransactionReceipt extends TableImpl<TransactionReceiptRecord> {

    private static final long serialVersionUID = 1208518553;

    /**
     * The reference instance of <code>public.transaction_receipt</code>
     */
    public static final TransactionReceipt TRANSACTION_RECEIPT = new TransactionReceipt();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TransactionReceiptRecord> getRecordType() {
        return TransactionReceiptRecord.class;
    }

    /**
     * The column <code>public.transaction_receipt.transaction_hash</code>.
     */
    public final TableField<TransactionReceiptRecord, String> TRANSACTION_HASH = createField("transaction_hash", org.jooq.impl.SQLDataType.CHAR(66).nullable(false), this, "");

    /**
     * The column <code>public.transaction_receipt.transaction_index</code>.
     */
    public final TableField<TransactionReceiptRecord, Integer> TRANSACTION_INDEX = createField("transaction_index", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.transaction_receipt.block_hash</code>.
     */
    public final TableField<TransactionReceiptRecord, String> BLOCK_HASH = createField("block_hash", org.jooq.impl.SQLDataType.CHAR(66).nullable(false), this, "");

    /**
     * The column <code>public.transaction_receipt.block_number</code>.
     */
    public final TableField<TransactionReceiptRecord, BigDecimal> BLOCK_NUMBER = createField("block_number", org.jooq.impl.SQLDataType.NUMERIC.nullable(false), this, "");

    /**
     * The column <code>public.transaction_receipt.from</code>.
     */
    public final TableField<TransactionReceiptRecord, String> FROM = createField("from", org.jooq.impl.SQLDataType.CHAR(42).nullable(false), this, "");

    /**
     * The column <code>public.transaction_receipt.to</code>.
     */
    public final TableField<TransactionReceiptRecord, String> TO = createField("to", org.jooq.impl.SQLDataType.CHAR(42), this, "");

    /**
     * The column <code>public.transaction_receipt.contract_address</code>.
     */
    public final TableField<TransactionReceiptRecord, String> CONTRACT_ADDRESS = createField("contract_address", org.jooq.impl.SQLDataType.CHAR(42), this, "");

    /**
     * The column <code>public.transaction_receipt.cumulative_gas_used</code>.
     */
    public final TableField<TransactionReceiptRecord, BigDecimal> CUMULATIVE_GAS_USED = createField("cumulative_gas_used", org.jooq.impl.SQLDataType.NUMERIC.nullable(false), this, "");

    /**
     * The column <code>public.transaction_receipt.gas_used</code>.
     */
    public final TableField<TransactionReceiptRecord, BigDecimal> GAS_USED = createField("gas_used", org.jooq.impl.SQLDataType.NUMERIC.nullable(false), this, "");

    /**
     * The column <code>public.transaction_receipt.logs</code>.
     */
    public final TableField<TransactionReceiptRecord, String> LOGS = createField("logs", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.transaction_receipt.logs_bloom</code>.
     */
    public final TableField<TransactionReceiptRecord, String> LOGS_BLOOM = createField("logs_bloom", org.jooq.impl.SQLDataType.CHAR(514).nullable(false), this, "");

    /**
     * The column <code>public.transaction_receipt.root</code>.
     */
    public final TableField<TransactionReceiptRecord, String> ROOT = createField("root", org.jooq.impl.SQLDataType.CHAR(66), this, "");

    /**
     * The column <code>public.transaction_receipt.status</code>.
     */
    public final TableField<TransactionReceiptRecord, String> STATUS = createField("status", org.jooq.impl.SQLDataType.VARCHAR(128), this, "");

    /**
     * The column <code>public.transaction_receipt.timestamp</code>.
     */
    public final TableField<TransactionReceiptRecord, Timestamp> TIMESTAMP = createField("timestamp", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * Create a <code>public.transaction_receipt</code> table reference
     */
    public TransactionReceipt() {
        this(DSL.name("transaction_receipt"), null);
    }

    /**
     * Create an aliased <code>public.transaction_receipt</code> table reference
     */
    public TransactionReceipt(String alias) {
        this(DSL.name(alias), TRANSACTION_RECEIPT);
    }

    /**
     * Create an aliased <code>public.transaction_receipt</code> table reference
     */
    public TransactionReceipt(Name alias) {
        this(alias, TRANSACTION_RECEIPT);
    }

    private TransactionReceipt(Name alias, Table<TransactionReceiptRecord> aliased) {
        this(alias, aliased, null);
    }

    private TransactionReceipt(Name alias, Table<TransactionReceiptRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> TransactionReceipt(Table<O> child, ForeignKey<O, TransactionReceiptRecord> key) {
        super(child, key, TRANSACTION_RECEIPT);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.IDX_RECEIPT_BY_BLOCK_NUMBER, Indexes.IDX_RECEIPT_BY_TX_HASH, Indexes.TRANSACTION_RECEIPT_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TransactionReceiptRecord> getPrimaryKey() {
        return Keys.TRANSACTION_RECEIPT_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TransactionReceiptRecord>> getKeys() {
        return Arrays.<UniqueKey<TransactionReceiptRecord>>asList(Keys.TRANSACTION_RECEIPT_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransactionReceipt as(String alias) {
        return new TransactionReceipt(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TransactionReceipt as(Name alias) {
        return new TransactionReceipt(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TransactionReceipt rename(String name) {
        return new TransactionReceipt(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TransactionReceipt rename(Name name) {
        return new TransactionReceipt(name, null);
    }
}
