/*
 * This file is generated by jOOQ.
 */
package com.ethvm.db.tables.records;


import com.ethvm.db.tables.AddressInternalTransactionCount;

import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AddressInternalTransactionCountRecord extends UpdatableRecordImpl<AddressInternalTransactionCountRecord> implements Record5<String, BigDecimal, Long, Long, Long> {

    private static final long serialVersionUID = 1096585312;

    /**
     * Setter for <code>public.address_internal_transaction_count.address</code>.
     */
    public AddressInternalTransactionCountRecord setAddress(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.address_internal_transaction_count.address</code>.
     */
    public String getAddress() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.address_internal_transaction_count.block_number</code>.
     */
    public AddressInternalTransactionCountRecord setBlockNumber(BigDecimal value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.address_internal_transaction_count.block_number</code>.
     */
    public BigDecimal getBlockNumber() {
        return (BigDecimal) get(1);
    }

    /**
     * Setter for <code>public.address_internal_transaction_count.total</code>.
     */
    public AddressInternalTransactionCountRecord setTotal(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.address_internal_transaction_count.total</code>.
     */
    public Long getTotal() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.address_internal_transaction_count.total_out</code>.
     */
    public AddressInternalTransactionCountRecord setTotalOut(Long value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.address_internal_transaction_count.total_out</code>.
     */
    public Long getTotalOut() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.address_internal_transaction_count.total_in</code>.
     */
    public AddressInternalTransactionCountRecord setTotalIn(Long value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.address_internal_transaction_count.total_in</code>.
     */
    public Long getTotalIn() {
        return (Long) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<String, BigDecimal> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<String, BigDecimal, Long, Long, Long> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<String, BigDecimal, Long, Long, Long> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return AddressInternalTransactionCount.ADDRESS_INTERNAL_TRANSACTION_COUNT.ADDRESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field2() {
        return AddressInternalTransactionCount.ADDRESS_INTERNAL_TRANSACTION_COUNT.BLOCK_NUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return AddressInternalTransactionCount.ADDRESS_INTERNAL_TRANSACTION_COUNT.TOTAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field4() {
        return AddressInternalTransactionCount.ADDRESS_INTERNAL_TRANSACTION_COUNT.TOTAL_OUT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5() {
        return AddressInternalTransactionCount.ADDRESS_INTERNAL_TRANSACTION_COUNT.TOTAL_IN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component2() {
        return getBlockNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component3() {
        return getTotal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component4() {
        return getTotalOut();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component5() {
        return getTotalIn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value2() {
        return getBlockNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getTotal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value4() {
        return getTotalOut();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5() {
        return getTotalIn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AddressInternalTransactionCountRecord value1(String value) {
        setAddress(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AddressInternalTransactionCountRecord value2(BigDecimal value) {
        setBlockNumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AddressInternalTransactionCountRecord value3(Long value) {
        setTotal(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AddressInternalTransactionCountRecord value4(Long value) {
        setTotalOut(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AddressInternalTransactionCountRecord value5(Long value) {
        setTotalIn(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AddressInternalTransactionCountRecord values(String value1, BigDecimal value2, Long value3, Long value4, Long value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AddressInternalTransactionCountRecord
     */
    public AddressInternalTransactionCountRecord() {
        super(AddressInternalTransactionCount.ADDRESS_INTERNAL_TRANSACTION_COUNT);
    }

    /**
     * Create a detached, initialised AddressInternalTransactionCountRecord
     */
    public AddressInternalTransactionCountRecord(String address, BigDecimal blockNumber, Long total, Long totalOut, Long totalIn) {
        super(AddressInternalTransactionCount.ADDRESS_INTERNAL_TRANSACTION_COUNT);

        set(0, address);
        set(1, blockNumber);
        set(2, total);
        set(3, totalOut);
        set(4, totalIn);
    }
}
