/*
 * This file is generated by jOOQ.
 */
package com.ethvm.db.tables.records;


import com.ethvm.db.tables.Balance;

import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BalanceRecord extends UpdatableRecordImpl<BalanceRecord> implements Record9<Long, String, BigDecimal, String, String, String, Timestamp, BigDecimal, BigDecimal> {

    private static final long serialVersionUID = -1167216131;

    /**
     * Setter for <code>public.balance.id</code>.
     */
    public BalanceRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.balance.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.balance.address</code>.
     */
    public BalanceRecord setAddress(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.balance.address</code>.
     */
    public String getAddress() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.balance.block_number</code>.
     */
    public BalanceRecord setBlockNumber(BigDecimal value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.balance.block_number</code>.
     */
    public BigDecimal getBlockNumber() {
        return (BigDecimal) get(2);
    }

    /**
     * Setter for <code>public.balance.block_hash</code>.
     */
    public BalanceRecord setBlockHash(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.balance.block_hash</code>.
     */
    public String getBlockHash() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.balance.contract_address</code>.
     */
    public BalanceRecord setContractAddress(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.balance.contract_address</code>.
     */
    public String getContractAddress() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.balance.token_type</code>.
     */
    public BalanceRecord setTokenType(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.balance.token_type</code>.
     */
    public String getTokenType() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.balance.timestamp</code>.
     */
    public BalanceRecord setTimestamp(Timestamp value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.balance.timestamp</code>.
     */
    public Timestamp getTimestamp() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>public.balance.balance</code>.
     */
    public BalanceRecord setBalance(BigDecimal value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.balance.balance</code>.
     */
    public BigDecimal getBalance() {
        return (BigDecimal) get(7);
    }

    /**
     * Setter for <code>public.balance.token_id</code>.
     */
    public BalanceRecord setTokenId(BigDecimal value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>public.balance.token_id</code>.
     */
    public BigDecimal getTokenId() {
        return (BigDecimal) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Long, String, BigDecimal, String, String, String, Timestamp, BigDecimal, BigDecimal> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Long, String, BigDecimal, String, String, String, Timestamp, BigDecimal, BigDecimal> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Balance.BALANCE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Balance.BALANCE.ADDRESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field3() {
        return Balance.BALANCE.BLOCK_NUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Balance.BALANCE.BLOCK_HASH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Balance.BALANCE.CONTRACT_ADDRESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Balance.BALANCE.TOKEN_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return Balance.BALANCE.TIMESTAMP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field8() {
        return Balance.BALANCE.BALANCE_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field9() {
        return Balance.BALANCE.TOKEN_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component3() {
        return getBlockNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getBlockHash();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getContractAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getTokenType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component7() {
        return getTimestamp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component8() {
        return getBalance();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component9() {
        return getTokenId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value3() {
        return getBlockNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getBlockHash();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getContractAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getTokenType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getTimestamp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value8() {
        return getBalance();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value9() {
        return getTokenId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BalanceRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BalanceRecord value2(String value) {
        setAddress(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BalanceRecord value3(BigDecimal value) {
        setBlockNumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BalanceRecord value4(String value) {
        setBlockHash(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BalanceRecord value5(String value) {
        setContractAddress(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BalanceRecord value6(String value) {
        setTokenType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BalanceRecord value7(Timestamp value) {
        setTimestamp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BalanceRecord value8(BigDecimal value) {
        setBalance(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BalanceRecord value9(BigDecimal value) {
        setTokenId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BalanceRecord values(Long value1, String value2, BigDecimal value3, String value4, String value5, String value6, Timestamp value7, BigDecimal value8, BigDecimal value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BalanceRecord
     */
    public BalanceRecord() {
        super(Balance.BALANCE);
    }

    /**
     * Create a detached, initialised BalanceRecord
     */
    public BalanceRecord(Long id, String address, BigDecimal blockNumber, String blockHash, String contractAddress, String tokenType, Timestamp timestamp, BigDecimal balance, BigDecimal tokenId) {
        super(Balance.BALANCE);

        set(0, id);
        set(1, address);
        set(2, blockNumber);
        set(3, blockHash);
        set(4, contractAddress);
        set(5, tokenType);
        set(6, timestamp);
        set(7, balance);
        set(8, tokenId);
    }
}
