/*
 * This file is generated by jOOQ.
 */
package com.ethvm.db.tables.records;


import com.ethvm.db.tables.BalanceDelta;

import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record15;
import org.jooq.Row15;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BalanceDeltaRecord extends UpdatableRecordImpl<BalanceDeltaRecord> implements Record15<Long, String, String, String, String, String, BigDecimal, BigDecimal, String, BigDecimal, Integer, String, String, Timestamp, Boolean> {

    private static final long serialVersionUID = 25812164;

    /**
     * Setter for <code>public.balance_delta.id</code>.
     */
    public BalanceDeltaRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.balance_delta.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.balance_delta.address</code>.
     */
    public BalanceDeltaRecord setAddress(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.balance_delta.address</code>.
     */
    public String getAddress() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.balance_delta.contract_address</code>.
     */
    public BalanceDeltaRecord setContractAddress(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.balance_delta.contract_address</code>.
     */
    public String getContractAddress() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.balance_delta.counterpart_address</code>.
     */
    public BalanceDeltaRecord setCounterpartAddress(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.balance_delta.counterpart_address</code>.
     */
    public String getCounterpartAddress() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.balance_delta.token_type</code>.
     */
    public BalanceDeltaRecord setTokenType(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.balance_delta.token_type</code>.
     */
    public String getTokenType() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.balance_delta.delta_type</code>.
     */
    public BalanceDeltaRecord setDeltaType(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.balance_delta.delta_type</code>.
     */
    public String getDeltaType() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.balance_delta.amount</code>.
     */
    public BalanceDeltaRecord setAmount(BigDecimal value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.balance_delta.amount</code>.
     */
    public BigDecimal getAmount() {
        return (BigDecimal) get(6);
    }

    /**
     * Setter for <code>public.balance_delta.token_id</code>.
     */
    public BalanceDeltaRecord setTokenId(BigDecimal value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.balance_delta.token_id</code>.
     */
    public BigDecimal getTokenId() {
        return (BigDecimal) get(7);
    }

    /**
     * Setter for <code>public.balance_delta.block_hash</code>.
     */
    public BalanceDeltaRecord setBlockHash(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>public.balance_delta.block_hash</code>.
     */
    public String getBlockHash() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.balance_delta.block_number</code>.
     */
    public BalanceDeltaRecord setBlockNumber(BigDecimal value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>public.balance_delta.block_number</code>.
     */
    public BigDecimal getBlockNumber() {
        return (BigDecimal) get(9);
    }

    /**
     * Setter for <code>public.balance_delta.transaction_index</code>.
     */
    public BalanceDeltaRecord setTransactionIndex(Integer value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>public.balance_delta.transaction_index</code>.
     */
    public Integer getTransactionIndex() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>public.balance_delta.transaction_hash</code>.
     */
    public BalanceDeltaRecord setTransactionHash(String value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>public.balance_delta.transaction_hash</code>.
     */
    public String getTransactionHash() {
        return (String) get(11);
    }

    /**
     * Setter for <code>public.balance_delta.trace_address</code>.
     */
    public BalanceDeltaRecord setTraceAddress(String value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>public.balance_delta.trace_address</code>.
     */
    public String getTraceAddress() {
        return (String) get(12);
    }

    /**
     * Setter for <code>public.balance_delta.timestamp</code>.
     */
    public BalanceDeltaRecord setTimestamp(Timestamp value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>public.balance_delta.timestamp</code>.
     */
    public Timestamp getTimestamp() {
        return (Timestamp) get(13);
    }

    /**
     * Setter for <code>public.balance_delta.is_receiving</code>.
     */
    public BalanceDeltaRecord setIsReceiving(Boolean value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for <code>public.balance_delta.is_receiving</code>.
     */
    public Boolean getIsReceiving() {
        return (Boolean) get(14);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record15 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row15<Long, String, String, String, String, String, BigDecimal, BigDecimal, String, BigDecimal, Integer, String, String, Timestamp, Boolean> fieldsRow() {
        return (Row15) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row15<Long, String, String, String, String, String, BigDecimal, BigDecimal, String, BigDecimal, Integer, String, String, Timestamp, Boolean> valuesRow() {
        return (Row15) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return BalanceDelta.BALANCE_DELTA.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return BalanceDelta.BALANCE_DELTA.ADDRESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return BalanceDelta.BALANCE_DELTA.CONTRACT_ADDRESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return BalanceDelta.BALANCE_DELTA.COUNTERPART_ADDRESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return BalanceDelta.BALANCE_DELTA.TOKEN_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return BalanceDelta.BALANCE_DELTA.DELTA_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field7() {
        return BalanceDelta.BALANCE_DELTA.AMOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field8() {
        return BalanceDelta.BALANCE_DELTA.TOKEN_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return BalanceDelta.BALANCE_DELTA.BLOCK_HASH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field10() {
        return BalanceDelta.BALANCE_DELTA.BLOCK_NUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field11() {
        return BalanceDelta.BALANCE_DELTA.TRANSACTION_INDEX;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return BalanceDelta.BALANCE_DELTA.TRANSACTION_HASH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return BalanceDelta.BALANCE_DELTA.TRACE_ADDRESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field14() {
        return BalanceDelta.BALANCE_DELTA.TIMESTAMP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field15() {
        return BalanceDelta.BALANCE_DELTA.IS_RECEIVING;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getContractAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getCounterpartAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getTokenType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getDeltaType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component7() {
        return getAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component8() {
        return getTokenId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getBlockHash();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component10() {
        return getBlockNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component11() {
        return getTransactionIndex();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component12() {
        return getTransactionHash();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component13() {
        return getTraceAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component14() {
        return getTimestamp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component15() {
        return getIsReceiving();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getContractAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getCounterpartAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getTokenType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getDeltaType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value7() {
        return getAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value8() {
        return getTokenId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getBlockHash();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value10() {
        return getBlockNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value11() {
        return getTransactionIndex();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getTransactionHash();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getTraceAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value14() {
        return getTimestamp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value15() {
        return getIsReceiving();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BalanceDeltaRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BalanceDeltaRecord value2(String value) {
        setAddress(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BalanceDeltaRecord value3(String value) {
        setContractAddress(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BalanceDeltaRecord value4(String value) {
        setCounterpartAddress(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BalanceDeltaRecord value5(String value) {
        setTokenType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BalanceDeltaRecord value6(String value) {
        setDeltaType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BalanceDeltaRecord value7(BigDecimal value) {
        setAmount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BalanceDeltaRecord value8(BigDecimal value) {
        setTokenId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BalanceDeltaRecord value9(String value) {
        setBlockHash(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BalanceDeltaRecord value10(BigDecimal value) {
        setBlockNumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BalanceDeltaRecord value11(Integer value) {
        setTransactionIndex(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BalanceDeltaRecord value12(String value) {
        setTransactionHash(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BalanceDeltaRecord value13(String value) {
        setTraceAddress(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BalanceDeltaRecord value14(Timestamp value) {
        setTimestamp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BalanceDeltaRecord value15(Boolean value) {
        setIsReceiving(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BalanceDeltaRecord values(Long value1, String value2, String value3, String value4, String value5, String value6, BigDecimal value7, BigDecimal value8, String value9, BigDecimal value10, Integer value11, String value12, String value13, Timestamp value14, Boolean value15) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BalanceDeltaRecord
     */
    public BalanceDeltaRecord() {
        super(BalanceDelta.BALANCE_DELTA);
    }

    /**
     * Create a detached, initialised BalanceDeltaRecord
     */
    public BalanceDeltaRecord(Long id, String address, String contractAddress, String counterpartAddress, String tokenType, String deltaType, BigDecimal amount, BigDecimal tokenId, String blockHash, BigDecimal blockNumber, Integer transactionIndex, String transactionHash, String traceAddress, Timestamp timestamp, Boolean isReceiving) {
        super(BalanceDelta.BALANCE_DELTA);

        set(0, id);
        set(1, address);
        set(2, contractAddress);
        set(3, counterpartAddress);
        set(4, tokenType);
        set(5, deltaType);
        set(6, amount);
        set(7, tokenId);
        set(8, blockHash);
        set(9, blockNumber);
        set(10, transactionIndex);
        set(11, transactionHash);
        set(12, traceAddress);
        set(13, timestamp);
        set(14, isReceiving);
    }
}
