/*
 * This file is generated by jOOQ.
 */
package com.ethvm.db.tables.records;


import com.ethvm.db.tables.CoinExchangeRate;

import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CoinExchangeRateRecord extends UpdatableRecordImpl<CoinExchangeRateRecord> implements Record7<String, String, BigDecimal, BigDecimal, BigDecimal, BigDecimal, Long> {

    private static final long serialVersionUID = 1059643160;

    /**
     * Setter for <code>public.coin_exchange_rate.id</code>.
     */
    public CoinExchangeRateRecord setId(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.coin_exchange_rate.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.coin_exchange_rate.currency</code>.
     */
    public CoinExchangeRateRecord setCurrency(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.coin_exchange_rate.currency</code>.
     */
    public String getCurrency() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.coin_exchange_rate.price</code>.
     */
    public CoinExchangeRateRecord setPrice(BigDecimal value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.coin_exchange_rate.price</code>.
     */
    public BigDecimal getPrice() {
        return (BigDecimal) get(2);
    }

    /**
     * Setter for <code>public.coin_exchange_rate.market_cap</code>.
     */
    public CoinExchangeRateRecord setMarketCap(BigDecimal value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.coin_exchange_rate.market_cap</code>.
     */
    public BigDecimal getMarketCap() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>public.coin_exchange_rate.vol24h</code>.
     */
    public CoinExchangeRateRecord setVol24h(BigDecimal value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.coin_exchange_rate.vol24h</code>.
     */
    public BigDecimal getVol24h() {
        return (BigDecimal) get(4);
    }

    /**
     * Setter for <code>public.coin_exchange_rate.change24h</code>.
     */
    public CoinExchangeRateRecord setChange24h(BigDecimal value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.coin_exchange_rate.change24h</code>.
     */
    public BigDecimal getChange24h() {
        return (BigDecimal) get(5);
    }

    /**
     * Setter for <code>public.coin_exchange_rate.last_updated</code>.
     */
    public CoinExchangeRateRecord setLastUpdated(Long value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.coin_exchange_rate.last_updated</code>.
     */
    public Long getLastUpdated() {
        return (Long) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<String, String, BigDecimal, BigDecimal, BigDecimal, BigDecimal, Long> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<String, String, BigDecimal, BigDecimal, BigDecimal, BigDecimal, Long> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return CoinExchangeRate.COIN_EXCHANGE_RATE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return CoinExchangeRate.COIN_EXCHANGE_RATE.CURRENCY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field3() {
        return CoinExchangeRate.COIN_EXCHANGE_RATE.PRICE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field4() {
        return CoinExchangeRate.COIN_EXCHANGE_RATE.MARKET_CAP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field5() {
        return CoinExchangeRate.COIN_EXCHANGE_RATE.VOL24H;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field6() {
        return CoinExchangeRate.COIN_EXCHANGE_RATE.CHANGE24H;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field7() {
        return CoinExchangeRate.COIN_EXCHANGE_RATE.LAST_UPDATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getCurrency();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component3() {
        return getPrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component4() {
        return getMarketCap();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component5() {
        return getVol24h();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component6() {
        return getChange24h();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component7() {
        return getLastUpdated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getCurrency();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value3() {
        return getPrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value4() {
        return getMarketCap();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value5() {
        return getVol24h();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value6() {
        return getChange24h();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value7() {
        return getLastUpdated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CoinExchangeRateRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CoinExchangeRateRecord value2(String value) {
        setCurrency(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CoinExchangeRateRecord value3(BigDecimal value) {
        setPrice(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CoinExchangeRateRecord value4(BigDecimal value) {
        setMarketCap(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CoinExchangeRateRecord value5(BigDecimal value) {
        setVol24h(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CoinExchangeRateRecord value6(BigDecimal value) {
        setChange24h(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CoinExchangeRateRecord value7(Long value) {
        setLastUpdated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CoinExchangeRateRecord values(String value1, String value2, BigDecimal value3, BigDecimal value4, BigDecimal value5, BigDecimal value6, Long value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CoinExchangeRateRecord
     */
    public CoinExchangeRateRecord() {
        super(CoinExchangeRate.COIN_EXCHANGE_RATE);
    }

    /**
     * Create a detached, initialised CoinExchangeRateRecord
     */
    public CoinExchangeRateRecord(String id, String currency, BigDecimal price, BigDecimal marketCap, BigDecimal vol24h, BigDecimal change24h, Long lastUpdated) {
        super(CoinExchangeRate.COIN_EXCHANGE_RATE);

        set(0, id);
        set(1, currency);
        set(2, price);
        set(3, marketCap);
        set(4, vol24h);
        set(5, change24h);
        set(6, lastUpdated);
    }
}
