/*
 * This file is generated by jOOQ.
 */
package com.ethvm.db.tables.records;


import com.ethvm.db.tables.Contract;

import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record17;
import org.jooq.Row17;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContractRecord extends UpdatableRecordImpl<ContractRecord> implements Record17<String, String, String, String, String, String, BigDecimal, String, BigDecimal, String, String, Timestamp, String, BigDecimal, String, String, Timestamp> {

    private static final long serialVersionUID = 183391653;

    /**
     * Setter for <code>public.contract.address</code>.
     */
    public ContractRecord setAddress(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.contract.address</code>.
     */
    public String getAddress() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.contract.creator</code>.
     */
    public ContractRecord setCreator(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.contract.creator</code>.
     */
    public String getCreator() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.contract.init</code>.
     */
    public ContractRecord setInit(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.contract.init</code>.
     */
    public String getInit() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.contract.code</code>.
     */
    public ContractRecord setCode(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.contract.code</code>.
     */
    public String getCode() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.contract.contract_type</code>.
     */
    public ContractRecord setContractType(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.contract.contract_type</code>.
     */
    public String getContractType() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.contract.refund_address</code>.
     */
    public ContractRecord setRefundAddress(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.contract.refund_address</code>.
     */
    public String getRefundAddress() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.contract.refund_balance</code>.
     */
    public ContractRecord setRefundBalance(BigDecimal value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.contract.refund_balance</code>.
     */
    public BigDecimal getRefundBalance() {
        return (BigDecimal) get(6);
    }

    /**
     * Setter for <code>public.contract.created_at_block_hash</code>.
     */
    public ContractRecord setCreatedAtBlockHash(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.contract.created_at_block_hash</code>.
     */
    public String getCreatedAtBlockHash() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.contract.created_at_block_number</code>.
     */
    public ContractRecord setCreatedAtBlockNumber(BigDecimal value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>public.contract.created_at_block_number</code>.
     */
    public BigDecimal getCreatedAtBlockNumber() {
        return (BigDecimal) get(8);
    }

    /**
     * Setter for <code>public.contract.created_at_transaction_hash</code>.
     */
    public ContractRecord setCreatedAtTransactionHash(String value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>public.contract.created_at_transaction_hash</code>.
     */
    public String getCreatedAtTransactionHash() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.contract.created_at_trace_address</code>.
     */
    public ContractRecord setCreatedAtTraceAddress(String value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>public.contract.created_at_trace_address</code>.
     */
    public String getCreatedAtTraceAddress() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.contract.created_at_timestamp</code>.
     */
    public ContractRecord setCreatedAtTimestamp(Timestamp value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>public.contract.created_at_timestamp</code>.
     */
    public Timestamp getCreatedAtTimestamp() {
        return (Timestamp) get(11);
    }

    /**
     * Setter for <code>public.contract.destroyed_at_block_hash</code>.
     */
    public ContractRecord setDestroyedAtBlockHash(String value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>public.contract.destroyed_at_block_hash</code>.
     */
    public String getDestroyedAtBlockHash() {
        return (String) get(12);
    }

    /**
     * Setter for <code>public.contract.destroyed_at_block_number</code>.
     */
    public ContractRecord setDestroyedAtBlockNumber(BigDecimal value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>public.contract.destroyed_at_block_number</code>.
     */
    public BigDecimal getDestroyedAtBlockNumber() {
        return (BigDecimal) get(13);
    }

    /**
     * Setter for <code>public.contract.destroyed_at_transaction_hash</code>.
     */
    public ContractRecord setDestroyedAtTransactionHash(String value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for <code>public.contract.destroyed_at_transaction_hash</code>.
     */
    public String getDestroyedAtTransactionHash() {
        return (String) get(14);
    }

    /**
     * Setter for <code>public.contract.destroyed_at_trace_address</code>.
     */
    public ContractRecord setDestroyedAtTraceAddress(String value) {
        set(15, value);
        return this;
    }

    /**
     * Getter for <code>public.contract.destroyed_at_trace_address</code>.
     */
    public String getDestroyedAtTraceAddress() {
        return (String) get(15);
    }

    /**
     * Setter for <code>public.contract.destroyed_at_timestamp</code>.
     */
    public ContractRecord setDestroyedAtTimestamp(Timestamp value) {
        set(16, value);
        return this;
    }

    /**
     * Getter for <code>public.contract.destroyed_at_timestamp</code>.
     */
    public Timestamp getDestroyedAtTimestamp() {
        return (Timestamp) get(16);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record17 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row17<String, String, String, String, String, String, BigDecimal, String, BigDecimal, String, String, Timestamp, String, BigDecimal, String, String, Timestamp> fieldsRow() {
        return (Row17) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row17<String, String, String, String, String, String, BigDecimal, String, BigDecimal, String, String, Timestamp, String, BigDecimal, String, String, Timestamp> valuesRow() {
        return (Row17) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Contract.CONTRACT.ADDRESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Contract.CONTRACT.CREATOR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Contract.CONTRACT.INIT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Contract.CONTRACT.CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Contract.CONTRACT.CONTRACT_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Contract.CONTRACT.REFUND_ADDRESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field7() {
        return Contract.CONTRACT.REFUND_BALANCE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Contract.CONTRACT.CREATED_AT_BLOCK_HASH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field9() {
        return Contract.CONTRACT.CREATED_AT_BLOCK_NUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return Contract.CONTRACT.CREATED_AT_TRANSACTION_HASH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return Contract.CONTRACT.CREATED_AT_TRACE_ADDRESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field12() {
        return Contract.CONTRACT.CREATED_AT_TIMESTAMP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return Contract.CONTRACT.DESTROYED_AT_BLOCK_HASH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field14() {
        return Contract.CONTRACT.DESTROYED_AT_BLOCK_NUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field15() {
        return Contract.CONTRACT.DESTROYED_AT_TRANSACTION_HASH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field16() {
        return Contract.CONTRACT.DESTROYED_AT_TRACE_ADDRESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field17() {
        return Contract.CONTRACT.DESTROYED_AT_TIMESTAMP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getCreator();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getInit();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getContractType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getRefundAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component7() {
        return getRefundBalance();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getCreatedAtBlockHash();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component9() {
        return getCreatedAtBlockNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getCreatedAtTransactionHash();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getCreatedAtTraceAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component12() {
        return getCreatedAtTimestamp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component13() {
        return getDestroyedAtBlockHash();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component14() {
        return getDestroyedAtBlockNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component15() {
        return getDestroyedAtTransactionHash();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component16() {
        return getDestroyedAtTraceAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component17() {
        return getDestroyedAtTimestamp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getCreator();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getInit();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getContractType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getRefundAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value7() {
        return getRefundBalance();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getCreatedAtBlockHash();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value9() {
        return getCreatedAtBlockNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getCreatedAtTransactionHash();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getCreatedAtTraceAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value12() {
        return getCreatedAtTimestamp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getDestroyedAtBlockHash();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value14() {
        return getDestroyedAtBlockNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value15() {
        return getDestroyedAtTransactionHash();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value16() {
        return getDestroyedAtTraceAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value17() {
        return getDestroyedAtTimestamp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractRecord value1(String value) {
        setAddress(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractRecord value2(String value) {
        setCreator(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractRecord value3(String value) {
        setInit(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractRecord value4(String value) {
        setCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractRecord value5(String value) {
        setContractType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractRecord value6(String value) {
        setRefundAddress(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractRecord value7(BigDecimal value) {
        setRefundBalance(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractRecord value8(String value) {
        setCreatedAtBlockHash(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractRecord value9(BigDecimal value) {
        setCreatedAtBlockNumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractRecord value10(String value) {
        setCreatedAtTransactionHash(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractRecord value11(String value) {
        setCreatedAtTraceAddress(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractRecord value12(Timestamp value) {
        setCreatedAtTimestamp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractRecord value13(String value) {
        setDestroyedAtBlockHash(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractRecord value14(BigDecimal value) {
        setDestroyedAtBlockNumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractRecord value15(String value) {
        setDestroyedAtTransactionHash(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractRecord value16(String value) {
        setDestroyedAtTraceAddress(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractRecord value17(Timestamp value) {
        setDestroyedAtTimestamp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractRecord values(String value1, String value2, String value3, String value4, String value5, String value6, BigDecimal value7, String value8, BigDecimal value9, String value10, String value11, Timestamp value12, String value13, BigDecimal value14, String value15, String value16, Timestamp value17) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ContractRecord
     */
    public ContractRecord() {
        super(Contract.CONTRACT);
    }

    /**
     * Create a detached, initialised ContractRecord
     */
    public ContractRecord(String address, String creator, String init, String code, String contractType, String refundAddress, BigDecimal refundBalance, String createdAtBlockHash, BigDecimal createdAtBlockNumber, String createdAtTransactionHash, String createdAtTraceAddress, Timestamp createdAtTimestamp, String destroyedAtBlockHash, BigDecimal destroyedAtBlockNumber, String destroyedAtTransactionHash, String destroyedAtTraceAddress, Timestamp destroyedAtTimestamp) {
        super(Contract.CONTRACT);

        set(0, address);
        set(1, creator);
        set(2, init);
        set(3, code);
        set(4, contractType);
        set(5, refundAddress);
        set(6, refundBalance);
        set(7, createdAtBlockHash);
        set(8, createdAtBlockNumber);
        set(9, createdAtTransactionHash);
        set(10, createdAtTraceAddress);
        set(11, createdAtTimestamp);
        set(12, destroyedAtBlockHash);
        set(13, destroyedAtBlockNumber);
        set(14, destroyedAtTransactionHash);
        set(15, destroyedAtTraceAddress);
        set(16, destroyedAtTimestamp);
    }
}
