/*
 * This file is generated by jOOQ.
 */
package com.ethvm.db.tables.records;


import com.ethvm.db.tables.ContractHolderCountDelta;

import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContractHolderCountDeltaRecord extends UpdatableRecordImpl<ContractHolderCountDeltaRecord> implements Record5<Long, String, String, BigDecimal, Integer> {

    private static final long serialVersionUID = 2081117249;

    /**
     * Setter for <code>public.contract_holder_count_delta.id</code>.
     */
    public ContractHolderCountDeltaRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.contract_holder_count_delta.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.contract_holder_count_delta.contract_address</code>.
     */
    public ContractHolderCountDeltaRecord setContractAddress(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.contract_holder_count_delta.contract_address</code>.
     */
    public String getContractAddress() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.contract_holder_count_delta.token_type</code>.
     */
    public ContractHolderCountDeltaRecord setTokenType(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.contract_holder_count_delta.token_type</code>.
     */
    public String getTokenType() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.contract_holder_count_delta.block_number</code>.
     */
    public ContractHolderCountDeltaRecord setBlockNumber(BigDecimal value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.contract_holder_count_delta.block_number</code>.
     */
    public BigDecimal getBlockNumber() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>public.contract_holder_count_delta.delta</code>.
     */
    public ContractHolderCountDeltaRecord setDelta(Integer value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.contract_holder_count_delta.delta</code>.
     */
    public Integer getDelta() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Long, String, String, BigDecimal, Integer> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Long, String, String, BigDecimal, Integer> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return ContractHolderCountDelta.CONTRACT_HOLDER_COUNT_DELTA.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return ContractHolderCountDelta.CONTRACT_HOLDER_COUNT_DELTA.CONTRACT_ADDRESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return ContractHolderCountDelta.CONTRACT_HOLDER_COUNT_DELTA.TOKEN_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field4() {
        return ContractHolderCountDelta.CONTRACT_HOLDER_COUNT_DELTA.BLOCK_NUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return ContractHolderCountDelta.CONTRACT_HOLDER_COUNT_DELTA.DELTA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getContractAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getTokenType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component4() {
        return getBlockNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getDelta();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getContractAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getTokenType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value4() {
        return getBlockNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getDelta();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractHolderCountDeltaRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractHolderCountDeltaRecord value2(String value) {
        setContractAddress(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractHolderCountDeltaRecord value3(String value) {
        setTokenType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractHolderCountDeltaRecord value4(BigDecimal value) {
        setBlockNumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractHolderCountDeltaRecord value5(Integer value) {
        setDelta(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ContractHolderCountDeltaRecord values(Long value1, String value2, String value3, BigDecimal value4, Integer value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ContractHolderCountDeltaRecord
     */
    public ContractHolderCountDeltaRecord() {
        super(ContractHolderCountDelta.CONTRACT_HOLDER_COUNT_DELTA);
    }

    /**
     * Create a detached, initialised ContractHolderCountDeltaRecord
     */
    public ContractHolderCountDeltaRecord(Long id, String contractAddress, String tokenType, BigDecimal blockNumber, Integer delta) {
        super(ContractHolderCountDelta.CONTRACT_HOLDER_COUNT_DELTA);

        set(0, id);
        set(1, contractAddress);
        set(2, tokenType);
        set(3, blockNumber);
        set(4, delta);
    }
}
