/*
 * This file is generated by jOOQ.
 */
package com.ethvm.db.tables.records;


import com.ethvm.db.tables.ForkUncleBalanceDelta;

import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record15;
import org.jooq.Row15;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ForkUncleBalanceDeltaRecord extends TableRecordImpl<ForkUncleBalanceDeltaRecord> implements Record15<Long, String, String, String, String, String, BigDecimal, BigDecimal, String, BigDecimal, Integer, String, String, Timestamp, Boolean> {

    private static final long serialVersionUID = 1690865196;

    /**
     * Setter for <code>public.fork_uncle_balance_delta.id</code>.
     */
    public ForkUncleBalanceDeltaRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.fork_uncle_balance_delta.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.fork_uncle_balance_delta.address</code>.
     */
    public ForkUncleBalanceDeltaRecord setAddress(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.fork_uncle_balance_delta.address</code>.
     */
    public String getAddress() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.fork_uncle_balance_delta.contract_address</code>.
     */
    public ForkUncleBalanceDeltaRecord setContractAddress(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.fork_uncle_balance_delta.contract_address</code>.
     */
    public String getContractAddress() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.fork_uncle_balance_delta.counterpart_address</code>.
     */
    public ForkUncleBalanceDeltaRecord setCounterpartAddress(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.fork_uncle_balance_delta.counterpart_address</code>.
     */
    public String getCounterpartAddress() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.fork_uncle_balance_delta.token_type</code>.
     */
    public ForkUncleBalanceDeltaRecord setTokenType(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.fork_uncle_balance_delta.token_type</code>.
     */
    public String getTokenType() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.fork_uncle_balance_delta.delta_type</code>.
     */
    public ForkUncleBalanceDeltaRecord setDeltaType(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.fork_uncle_balance_delta.delta_type</code>.
     */
    public String getDeltaType() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.fork_uncle_balance_delta.amount</code>.
     */
    public ForkUncleBalanceDeltaRecord setAmount(BigDecimal value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.fork_uncle_balance_delta.amount</code>.
     */
    public BigDecimal getAmount() {
        return (BigDecimal) get(6);
    }

    /**
     * Setter for <code>public.fork_uncle_balance_delta.token_id</code>.
     */
    public ForkUncleBalanceDeltaRecord setTokenId(BigDecimal value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.fork_uncle_balance_delta.token_id</code>.
     */
    public BigDecimal getTokenId() {
        return (BigDecimal) get(7);
    }

    /**
     * Setter for <code>public.fork_uncle_balance_delta.block_hash</code>.
     */
    public ForkUncleBalanceDeltaRecord setBlockHash(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>public.fork_uncle_balance_delta.block_hash</code>.
     */
    public String getBlockHash() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.fork_uncle_balance_delta.block_number</code>.
     */
    public ForkUncleBalanceDeltaRecord setBlockNumber(BigDecimal value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>public.fork_uncle_balance_delta.block_number</code>.
     */
    public BigDecimal getBlockNumber() {
        return (BigDecimal) get(9);
    }

    /**
     * Setter for <code>public.fork_uncle_balance_delta.transaction_index</code>.
     */
    public ForkUncleBalanceDeltaRecord setTransactionIndex(Integer value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>public.fork_uncle_balance_delta.transaction_index</code>.
     */
    public Integer getTransactionIndex() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>public.fork_uncle_balance_delta.transaction_hash</code>.
     */
    public ForkUncleBalanceDeltaRecord setTransactionHash(String value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>public.fork_uncle_balance_delta.transaction_hash</code>.
     */
    public String getTransactionHash() {
        return (String) get(11);
    }

    /**
     * Setter for <code>public.fork_uncle_balance_delta.trace_address</code>.
     */
    public ForkUncleBalanceDeltaRecord setTraceAddress(String value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>public.fork_uncle_balance_delta.trace_address</code>.
     */
    public String getTraceAddress() {
        return (String) get(12);
    }

    /**
     * Setter for <code>public.fork_uncle_balance_delta.timestamp</code>.
     */
    public ForkUncleBalanceDeltaRecord setTimestamp(Timestamp value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>public.fork_uncle_balance_delta.timestamp</code>.
     */
    public Timestamp getTimestamp() {
        return (Timestamp) get(13);
    }

    /**
     * Setter for <code>public.fork_uncle_balance_delta.is_receiving</code>.
     */
    public ForkUncleBalanceDeltaRecord setIsReceiving(Boolean value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for <code>public.fork_uncle_balance_delta.is_receiving</code>.
     */
    public Boolean getIsReceiving() {
        return (Boolean) get(14);
    }

    // -------------------------------------------------------------------------
    // Record15 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row15<Long, String, String, String, String, String, BigDecimal, BigDecimal, String, BigDecimal, Integer, String, String, Timestamp, Boolean> fieldsRow() {
        return (Row15) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row15<Long, String, String, String, String, String, BigDecimal, BigDecimal, String, BigDecimal, Integer, String, String, Timestamp, Boolean> valuesRow() {
        return (Row15) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return ForkUncleBalanceDelta.FORK_UNCLE_BALANCE_DELTA.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return ForkUncleBalanceDelta.FORK_UNCLE_BALANCE_DELTA.ADDRESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return ForkUncleBalanceDelta.FORK_UNCLE_BALANCE_DELTA.CONTRACT_ADDRESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return ForkUncleBalanceDelta.FORK_UNCLE_BALANCE_DELTA.COUNTERPART_ADDRESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return ForkUncleBalanceDelta.FORK_UNCLE_BALANCE_DELTA.TOKEN_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return ForkUncleBalanceDelta.FORK_UNCLE_BALANCE_DELTA.DELTA_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field7() {
        return ForkUncleBalanceDelta.FORK_UNCLE_BALANCE_DELTA.AMOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field8() {
        return ForkUncleBalanceDelta.FORK_UNCLE_BALANCE_DELTA.TOKEN_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return ForkUncleBalanceDelta.FORK_UNCLE_BALANCE_DELTA.BLOCK_HASH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field10() {
        return ForkUncleBalanceDelta.FORK_UNCLE_BALANCE_DELTA.BLOCK_NUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field11() {
        return ForkUncleBalanceDelta.FORK_UNCLE_BALANCE_DELTA.TRANSACTION_INDEX;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return ForkUncleBalanceDelta.FORK_UNCLE_BALANCE_DELTA.TRANSACTION_HASH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return ForkUncleBalanceDelta.FORK_UNCLE_BALANCE_DELTA.TRACE_ADDRESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field14() {
        return ForkUncleBalanceDelta.FORK_UNCLE_BALANCE_DELTA.TIMESTAMP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field15() {
        return ForkUncleBalanceDelta.FORK_UNCLE_BALANCE_DELTA.IS_RECEIVING;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getContractAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getCounterpartAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getTokenType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getDeltaType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component7() {
        return getAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component8() {
        return getTokenId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getBlockHash();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component10() {
        return getBlockNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component11() {
        return getTransactionIndex();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component12() {
        return getTransactionHash();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component13() {
        return getTraceAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component14() {
        return getTimestamp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component15() {
        return getIsReceiving();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getContractAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getCounterpartAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getTokenType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getDeltaType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value7() {
        return getAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value8() {
        return getTokenId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getBlockHash();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value10() {
        return getBlockNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value11() {
        return getTransactionIndex();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getTransactionHash();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getTraceAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value14() {
        return getTimestamp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value15() {
        return getIsReceiving();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ForkUncleBalanceDeltaRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ForkUncleBalanceDeltaRecord value2(String value) {
        setAddress(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ForkUncleBalanceDeltaRecord value3(String value) {
        setContractAddress(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ForkUncleBalanceDeltaRecord value4(String value) {
        setCounterpartAddress(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ForkUncleBalanceDeltaRecord value5(String value) {
        setTokenType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ForkUncleBalanceDeltaRecord value6(String value) {
        setDeltaType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ForkUncleBalanceDeltaRecord value7(BigDecimal value) {
        setAmount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ForkUncleBalanceDeltaRecord value8(BigDecimal value) {
        setTokenId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ForkUncleBalanceDeltaRecord value9(String value) {
        setBlockHash(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ForkUncleBalanceDeltaRecord value10(BigDecimal value) {
        setBlockNumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ForkUncleBalanceDeltaRecord value11(Integer value) {
        setTransactionIndex(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ForkUncleBalanceDeltaRecord value12(String value) {
        setTransactionHash(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ForkUncleBalanceDeltaRecord value13(String value) {
        setTraceAddress(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ForkUncleBalanceDeltaRecord value14(Timestamp value) {
        setTimestamp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ForkUncleBalanceDeltaRecord value15(Boolean value) {
        setIsReceiving(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ForkUncleBalanceDeltaRecord values(Long value1, String value2, String value3, String value4, String value5, String value6, BigDecimal value7, BigDecimal value8, String value9, BigDecimal value10, Integer value11, String value12, String value13, Timestamp value14, Boolean value15) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ForkUncleBalanceDeltaRecord
     */
    public ForkUncleBalanceDeltaRecord() {
        super(ForkUncleBalanceDelta.FORK_UNCLE_BALANCE_DELTA);
    }

    /**
     * Create a detached, initialised ForkUncleBalanceDeltaRecord
     */
    public ForkUncleBalanceDeltaRecord(Long id, String address, String contractAddress, String counterpartAddress, String tokenType, String deltaType, BigDecimal amount, BigDecimal tokenId, String blockHash, BigDecimal blockNumber, Integer transactionIndex, String transactionHash, String traceAddress, Timestamp timestamp, Boolean isReceiving) {
        super(ForkUncleBalanceDelta.FORK_UNCLE_BALANCE_DELTA);

        set(0, id);
        set(1, address);
        set(2, contractAddress);
        set(3, counterpartAddress);
        set(4, tokenType);
        set(5, deltaType);
        set(6, amount);
        set(7, tokenId);
        set(8, blockHash);
        set(9, blockNumber);
        set(10, transactionIndex);
        set(11, transactionHash);
        set(12, traceAddress);
        set(13, timestamp);
        set(14, isReceiving);
    }
}
