/*
 * This file is generated by jOOQ.
 */
package com.ethvm.db.tables.records;


import com.ethvm.db.tables.MinerBlockCount;

import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MinerBlockCountRecord extends UpdatableRecordImpl<MinerBlockCountRecord> implements Record3<String, Long, BigDecimal> {

    private static final long serialVersionUID = 1521517217;

    /**
     * Setter for <code>public.miner_block_count.author</code>.
     */
    public MinerBlockCountRecord setAuthor(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.miner_block_count.author</code>.
     */
    public String getAuthor() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.miner_block_count.count</code>.
     */
    public MinerBlockCountRecord setCount(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.miner_block_count.count</code>.
     */
    public Long getCount() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.miner_block_count.block_number</code>.
     */
    public MinerBlockCountRecord setBlockNumber(BigDecimal value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.miner_block_count.block_number</code>.
     */
    public BigDecimal getBlockNumber() {
        return (BigDecimal) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<String, BigDecimal> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, Long, BigDecimal> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, Long, BigDecimal> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return MinerBlockCount.MINER_BLOCK_COUNT.AUTHOR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return MinerBlockCount.MINER_BLOCK_COUNT.COUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field3() {
        return MinerBlockCount.MINER_BLOCK_COUNT.BLOCK_NUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getAuthor();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component3() {
        return getBlockNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getAuthor();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value3() {
        return getBlockNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MinerBlockCountRecord value1(String value) {
        setAuthor(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MinerBlockCountRecord value2(Long value) {
        setCount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MinerBlockCountRecord value3(BigDecimal value) {
        setBlockNumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MinerBlockCountRecord values(String value1, Long value2, BigDecimal value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MinerBlockCountRecord
     */
    public MinerBlockCountRecord() {
        super(MinerBlockCount.MINER_BLOCK_COUNT);
    }

    /**
     * Create a detached, initialised MinerBlockCountRecord
     */
    public MinerBlockCountRecord(String author, Long count, BigDecimal blockNumber) {
        super(MinerBlockCount.MINER_BLOCK_COUNT);

        set(0, author);
        set(1, count);
        set(2, blockNumber);
    }
}
