/*
 * This file is generated by jOOQ.
 */
package com.ethvm.db.tables.records;


import com.ethvm.db.tables.ProcessorHashLog;

import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProcessorHashLogRecord extends UpdatableRecordImpl<ProcessorHashLogRecord> implements Record3<String, BigDecimal, String> {

    private static final long serialVersionUID = -1695662196;

    /**
     * Setter for <code>public.processor_hash_log.processor_id</code>.
     */
    public ProcessorHashLogRecord setProcessorId(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.processor_hash_log.processor_id</code>.
     */
    public String getProcessorId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.processor_hash_log.block_number</code>.
     */
    public ProcessorHashLogRecord setBlockNumber(BigDecimal value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.processor_hash_log.block_number</code>.
     */
    public BigDecimal getBlockNumber() {
        return (BigDecimal) get(1);
    }

    /**
     * Setter for <code>public.processor_hash_log.block_hash</code>.
     */
    public ProcessorHashLogRecord setBlockHash(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.processor_hash_log.block_hash</code>.
     */
    public String getBlockHash() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<String, BigDecimal> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, BigDecimal, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, BigDecimal, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return ProcessorHashLog.PROCESSOR_HASH_LOG.PROCESSOR_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field2() {
        return ProcessorHashLog.PROCESSOR_HASH_LOG.BLOCK_NUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return ProcessorHashLog.PROCESSOR_HASH_LOG.BLOCK_HASH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getProcessorId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component2() {
        return getBlockNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getBlockHash();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getProcessorId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value2() {
        return getBlockNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getBlockHash();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProcessorHashLogRecord value1(String value) {
        setProcessorId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProcessorHashLogRecord value2(BigDecimal value) {
        setBlockNumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProcessorHashLogRecord value3(String value) {
        setBlockHash(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProcessorHashLogRecord values(String value1, BigDecimal value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProcessorHashLogRecord
     */
    public ProcessorHashLogRecord() {
        super(ProcessorHashLog.PROCESSOR_HASH_LOG);
    }

    /**
     * Create a detached, initialised ProcessorHashLogRecord
     */
    public ProcessorHashLogRecord(String processorId, BigDecimal blockNumber, String blockHash) {
        super(ProcessorHashLog.PROCESSOR_HASH_LOG);

        set(0, processorId);
        set(1, blockNumber);
        set(2, blockHash);
    }
}
