/*
 * This file is generated by jOOQ.
 */
package com.ethvm.db.tables.records;


import com.ethvm.db.tables.Trace;

import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TraceRecord extends TableRecordImpl<TraceRecord> implements Record7<BigDecimal, String, String, String, Timestamp, Integer, String> {

    private static final long serialVersionUID = 1606952429;

    /**
     * Setter for <code>public.trace.block_number</code>.
     */
    public TraceRecord setBlockNumber(BigDecimal value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.trace.block_number</code>.
     */
    public BigDecimal getBlockNumber() {
        return (BigDecimal) get(0);
    }

    /**
     * Setter for <code>public.trace.block_hash</code>.
     */
    public TraceRecord setBlockHash(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.trace.block_hash</code>.
     */
    public String getBlockHash() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.trace.transaction_hash</code>.
     */
    public TraceRecord setTransactionHash(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.trace.transaction_hash</code>.
     */
    public String getTransactionHash() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.trace.root_error</code>.
     */
    public TraceRecord setRootError(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.trace.root_error</code>.
     */
    public String getRootError() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.trace.timestamp</code>.
     */
    public TraceRecord setTimestamp(Timestamp value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.trace.timestamp</code>.
     */
    public Timestamp getTimestamp() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>public.trace.trace_count</code>.
     */
    public TraceRecord setTraceCount(Integer value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.trace.trace_count</code>.
     */
    public Integer getTraceCount() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>public.trace.traces</code>.
     */
    public TraceRecord setTraces(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.trace.traces</code>.
     */
    public String getTraces() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<BigDecimal, String, String, String, Timestamp, Integer, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<BigDecimal, String, String, String, Timestamp, Integer, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field1() {
        return Trace.TRACE.BLOCK_NUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Trace.TRACE.BLOCK_HASH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Trace.TRACE.TRANSACTION_HASH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Trace.TRACE.ROOT_ERROR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return Trace.TRACE.TIMESTAMP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return Trace.TRACE.TRACE_COUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Trace.TRACE.TRACES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component1() {
        return getBlockNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getBlockHash();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getTransactionHash();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getRootError();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getTimestamp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getTraceCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getTraces();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value1() {
        return getBlockNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getBlockHash();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getTransactionHash();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getRootError();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getTimestamp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getTraceCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getTraces();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TraceRecord value1(BigDecimal value) {
        setBlockNumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TraceRecord value2(String value) {
        setBlockHash(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TraceRecord value3(String value) {
        setTransactionHash(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TraceRecord value4(String value) {
        setRootError(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TraceRecord value5(Timestamp value) {
        setTimestamp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TraceRecord value6(Integer value) {
        setTraceCount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TraceRecord value7(String value) {
        setTraces(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TraceRecord values(BigDecimal value1, String value2, String value3, String value4, Timestamp value5, Integer value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TraceRecord
     */
    public TraceRecord() {
        super(Trace.TRACE);
    }

    /**
     * Create a detached, initialised TraceRecord
     */
    public TraceRecord(BigDecimal blockNumber, String blockHash, String transactionHash, String rootError, Timestamp timestamp, Integer traceCount, String traces) {
        super(Trace.TRACE);

        set(0, blockNumber);
        set(1, blockHash);
        set(2, transactionHash);
        set(3, rootError);
        set(4, timestamp);
        set(5, traceCount);
        set(6, traces);
    }
}
