/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.enkrypt.bolt.models;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Log extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 2939691309127777290L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Log\",\"namespace\":\"io.enkrypt.bolt.models\",\"fields\":[{\"name\":\"address\",\"type\":\"string\",\"desc\":\"Address of the contract that generated the event\"},{\"name\":\"topics\",\"type\":{\"type\":\"array\",\"items\":\"string\"},\"desc\":\"List of topics provided by the contract\"},{\"name\":\"data\",\"type\":\"bytes\",\"desc\":\"Supplied by the contract, usually ABI-encoded\"},{\"name\":\"index\",\"type\":\"int\",\"desc\":\"Index of the log in the receipt\"},{\"name\":\"removed\",\"type\":\"boolean\",\"desc\":\"True if this log was reverted due to a chain reorganisation\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Log> ENCODER =
      new BinaryMessageEncoder<Log>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Log> DECODER =
      new BinaryMessageDecoder<Log>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<Log> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<Log> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Log>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this Log to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a Log from a ByteBuffer. */
  public static Log fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public CharSequence address;
  @Deprecated public java.util.List<CharSequence> topics;
  @Deprecated public java.nio.ByteBuffer data;
  @Deprecated public int index;
  @Deprecated public boolean removed;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Log() {}

  /**
   * All-args constructor.
   * @param address The new value for address
   * @param topics The new value for topics
   * @param data The new value for data
   * @param index The new value for index
   * @param removed The new value for removed
   */
  public Log(CharSequence address, java.util.List<CharSequence> topics, java.nio.ByteBuffer data, Integer index, Boolean removed) {
    this.address = address;
    this.topics = topics;
    this.data = data;
    this.index = index;
    this.removed = removed;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public Object get(int field$) {
    switch (field$) {
    case 0: return address;
    case 1: return topics;
    case 2: return data;
    case 3: return index;
    case 4: return removed;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, Object value$) {
    switch (field$) {
    case 0: address = (CharSequence)value$; break;
    case 1: topics = (java.util.List<CharSequence>)value$; break;
    case 2: data = (java.nio.ByteBuffer)value$; break;
    case 3: index = (Integer)value$; break;
    case 4: removed = (Boolean)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'address' field.
   * @return The value of the 'address' field.
   */
  public CharSequence getAddress() {
    return address;
  }

  /**
   * Sets the value of the 'address' field.
   * @param value the value to set.
   */
  public void setAddress(CharSequence value) {
    this.address = value;
  }

  /**
   * Gets the value of the 'topics' field.
   * @return The value of the 'topics' field.
   */
  public java.util.List<CharSequence> getTopics() {
    return topics;
  }

  /**
   * Sets the value of the 'topics' field.
   * @param value the value to set.
   */
  public void setTopics(java.util.List<CharSequence> value) {
    this.topics = value;
  }

  /**
   * Gets the value of the 'data' field.
   * @return The value of the 'data' field.
   */
  public java.nio.ByteBuffer getData() {
    return data;
  }

  /**
   * Sets the value of the 'data' field.
   * @param value the value to set.
   */
  public void setData(java.nio.ByteBuffer value) {
    this.data = value;
  }

  /**
   * Gets the value of the 'index' field.
   * @return The value of the 'index' field.
   */
  public Integer getIndex() {
    return index;
  }

  /**
   * Sets the value of the 'index' field.
   * @param value the value to set.
   */
  public void setIndex(Integer value) {
    this.index = value;
  }

  /**
   * Gets the value of the 'removed' field.
   * @return The value of the 'removed' field.
   */
  public Boolean getRemoved() {
    return removed;
  }

  /**
   * Sets the value of the 'removed' field.
   * @param value the value to set.
   */
  public void setRemoved(Boolean value) {
    this.removed = value;
  }

  /**
   * Creates a new Log RecordBuilder.
   * @return A new Log RecordBuilder
   */
  public static Builder newBuilder() {
    return new Builder();
  }

  /**
   * Creates a new Log RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Log RecordBuilder
   */
  public static Builder newBuilder(Builder other) {
    return new Builder(other);
  }

  /**
   * Creates a new Log RecordBuilder by copying an existing Log instance.
   * @param other The existing instance to copy.
   * @return A new Log RecordBuilder
   */
  public static Builder newBuilder(Log other) {
    return new Builder(other);
  }

  /**
   * RecordBuilder for Log instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Log>
    implements org.apache.avro.data.RecordBuilder<Log> {

    private CharSequence address;
    private java.util.List<CharSequence> topics;
    private java.nio.ByteBuffer data;
    private int index;
    private boolean removed;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.address)) {
        this.address = data().deepCopy(fields()[0].schema(), other.address);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.topics)) {
        this.topics = data().deepCopy(fields()[1].schema(), other.topics);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.data)) {
        this.data = data().deepCopy(fields()[2].schema(), other.data);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.index)) {
        this.index = data().deepCopy(fields()[3].schema(), other.index);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.removed)) {
        this.removed = data().deepCopy(fields()[4].schema(), other.removed);
        fieldSetFlags()[4] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing Log instance
     * @param other The existing instance to copy.
     */
    private Builder(Log other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.address)) {
        this.address = data().deepCopy(fields()[0].schema(), other.address);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.topics)) {
        this.topics = data().deepCopy(fields()[1].schema(), other.topics);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.data)) {
        this.data = data().deepCopy(fields()[2].schema(), other.data);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.index)) {
        this.index = data().deepCopy(fields()[3].schema(), other.index);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.removed)) {
        this.removed = data().deepCopy(fields()[4].schema(), other.removed);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'address' field.
      * @return The value.
      */
    public CharSequence getAddress() {
      return address;
    }

    /**
      * Sets the value of the 'address' field.
      * @param value The value of 'address'.
      * @return This builder.
      */
    public Builder setAddress(CharSequence value) {
      validate(fields()[0], value);
      this.address = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'address' field has been set.
      * @return True if the 'address' field has been set, false otherwise.
      */
    public boolean hasAddress() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'address' field.
      * @return This builder.
      */
    public Builder clearAddress() {
      address = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'topics' field.
      * @return The value.
      */
    public java.util.List<CharSequence> getTopics() {
      return topics;
    }

    /**
      * Sets the value of the 'topics' field.
      * @param value The value of 'topics'.
      * @return This builder.
      */
    public Builder setTopics(java.util.List<CharSequence> value) {
      validate(fields()[1], value);
      this.topics = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'topics' field has been set.
      * @return True if the 'topics' field has been set, false otherwise.
      */
    public boolean hasTopics() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'topics' field.
      * @return This builder.
      */
    public Builder clearTopics() {
      topics = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'data' field.
      * @return The value.
      */
    public java.nio.ByteBuffer getData() {
      return data;
    }

    /**
      * Sets the value of the 'data' field.
      * @param value The value of 'data'.
      * @return This builder.
      */
    public Builder setData(java.nio.ByteBuffer value) {
      validate(fields()[2], value);
      this.data = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'data' field has been set.
      * @return True if the 'data' field has been set, false otherwise.
      */
    public boolean hasData() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'data' field.
      * @return This builder.
      */
    public Builder clearData() {
      data = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'index' field.
      * @return The value.
      */
    public Integer getIndex() {
      return index;
    }

    /**
      * Sets the value of the 'index' field.
      * @param value The value of 'index'.
      * @return This builder.
      */
    public Builder setIndex(int value) {
      validate(fields()[3], value);
      this.index = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'index' field has been set.
      * @return True if the 'index' field has been set, false otherwise.
      */
    public boolean hasIndex() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'index' field.
      * @return This builder.
      */
    public Builder clearIndex() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'removed' field.
      * @return The value.
      */
    public Boolean getRemoved() {
      return removed;
    }

    /**
      * Sets the value of the 'removed' field.
      * @param value The value of 'removed'.
      * @return This builder.
      */
    public Builder setRemoved(boolean value) {
      validate(fields()[4], value);
      this.removed = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'removed' field has been set.
      * @return True if the 'removed' field has been set, false otherwise.
      */
    public boolean hasRemoved() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'removed' field.
      * @return This builder.
      */
    public Builder clearRemoved() {
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Log build() {
      try {
        Log record = new Log();
        record.address = fieldSetFlags()[0] ? this.address : (CharSequence) defaultValue(fields()[0]);
        record.topics = fieldSetFlags()[1] ? this.topics : (java.util.List<CharSequence>) defaultValue(fields()[1]);
        record.data = fieldSetFlags()[2] ? this.data : (java.nio.ByteBuffer) defaultValue(fields()[2]);
        record.index = fieldSetFlags()[3] ? this.index : (Integer) defaultValue(fields()[3]);
        record.removed = fieldSetFlags()[4] ? this.removed : (Boolean) defaultValue(fields()[4]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Log>
    WRITER$ = (org.apache.avro.io.DatumWriter<Log>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Log>
    READER$ = (org.apache.avro.io.DatumReader<Log>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
