/*
 * This file is generated by jOOQ.
 */
package com.ethvm.db;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.address_transaction_count_delta_id_seq</code>
     */
    public static final Sequence<Long> ADDRESS_TRANSACTION_COUNT_DELTA_ID_SEQ = new SequenceImpl<Long>("address_transaction_count_delta_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.balance_delta_id_seq</code>
     */
    public static final Sequence<Long> BALANCE_DELTA_ID_SEQ = new SequenceImpl<Long>("balance_delta_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.balance_id_seq</code>
     */
    public static final Sequence<Long> BALANCE_ID_SEQ = new SequenceImpl<Long>("balance_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));
}
