export const Events = {
    NEW_BLOCK: 'NEW_BLOCK',
    NEW_SIMPLE_BLOCK: 'NEW_SIMPLE_BLOCK',
    NEW_PENDING_TX: 'NEW_PENDING_TX',
    NEW_BLOCK_METRIC: 'NEW_BLOCK_METRIC',
    NEW_TX: 'NEW_TX',
    NEW_UNCLE: 'NEW_UNCLE'
}
