/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const SmallBlock = t.iface([], {
  "number": "number",
  "hash": "string",
});

export const Header = t.iface([], {
  "parentHash": "string",
  "unclesHash": t.opt("string"),
  "timestamp": t.opt("number"),
  "nonce": t.opt("string"),
  "miner": "string",
  "rewards": "any",
  "difficulty": t.opt("number"),
  "totalDifficulty": t.opt("number"),
  "stateRoot": "Buffer",
  "transactionsRoot": t.opt("Buffer"),
  "receiptsRoot": "Buffer",
  "logsBloom": t.opt("Buffer"),
  "gasLimit": t.opt("number"),
  "gasUsed": t.opt("number"),
  "mixHash": t.opt("Buffer"),
  "extraData": t.opt("Buffer"),
});

export const BlockStats = t.iface([], {
  "successfulTxs": t.opt("number"),
  "failedTxs": t.opt("number"),
  "pendingTxs": t.opt("number"),
  "processingTimeMs": t.opt("number"),
  "txs": t.opt("number"),
  "internalTxs": t.opt("number"),
  "avgGasPrice": t.opt("number"),
  "avgTxsFees": t.opt("number"),
  "totalGasPrice": t.opt("number"),
  "totalTxsFees": t.opt("number"),
});

export const Block = t.iface([], {
  "number": "number",
  "hash": "string",
  "header": "Header",
  "stats": "BlockStats",
  "transactions": t.opt(t.array("string")),
  "uncles": t.opt(t.array("string")),
});

const exportedTypeSuite: t.ITypeSuite = {
  SmallBlock,
  Header,
  BlockStats,
  Block,
};
export default exportedTypeSuite;
