FROM confluentinc/cp-kafka-connect-base:5.0.0

RUN confluent-hub install --no-prompt confluentinc/kafka-connect-jdbc:5.0.0
RUN confluent-hub install --no-prompt confluentinc/kafka-connect-elasticsearch:5.0.0
RUN confluent-hub install --no-prompt hpgrahsl/kafka-connect-mongodb:1.1.0
