FROM node:10.14.2-alpine

# Add repositories
RUN echo -e "http://uk.alpinelinux.org/alpine/v3.8/main\nhttp://uk.alpinelinux.org/alpine/v3.8/community" > /etc/apk/repositories

# Install deps
RUN apk add --no-cache bash make gcc musl-dev linux-headers git python g++

# Create workdir
RUN mkdir -p /var/explorer
WORKDIR /var/explorer
USER node

# Copy
COPY . .

# Remove cached node_modules
RUN rm -rf /var/explorer/node_modules

# Expose
EXPOSE 8080
CMD yarn install && yarn start:dev
