FROM confluentinc/cp-kafka-connect:5.2.0

RUN confluent-hub install confluentinc/kafka-connect-jdbc:5.2.0 --no-prompt \
  && wget -P /usr/share/java https://jdbc.postgresql.org/download/postgresql-42.2.5.jar
